version: "3.8"

services:
  makeapifront:
    container_name: make-api-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3888:3000"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
